//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZbcTemperatureApi.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZBCRoomInfoDbEntities1 : DbContext
    {
        public ZBCRoomInfoDbEntities1()
            : base("name=ZBCRoomInfoDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RoomTemperatures> RoomTemperatures { get; set; }
        public virtual DbSet<Temperature> Temperature { get; set; }
    }
}
